"""Add initial models

Revision ID: e690282050a1
Revises:
Create Date: 2021-09-09 17:27:04.631432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e690282050a1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "directors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_directors_id"), "directors", ["id"], unique=False)
    op.create_index(op.f("ix_directors_name"), "directors", ["name"], unique=True)
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("imdb_id", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("imdb_rating", sa.Float(), nullable=True),
        sa.Column("imdb_rating_count", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movies_id"), "movies", ["id"], unique=False)
    op.create_index(op.f("ix_movies_imdb_id"), "movies", ["imdb_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_movies_imdb_id"), table_name="movies")
    op.drop_index(op.f("ix_movies_id"), table_name="movies")
    op.drop_table("movies")
    op.drop_index(op.f("ix_directors_name"), table_name="directors")
    op.drop_index(op.f("ix_directors_id"), table_name="directors")
    op.drop_table("directors")
    # ### end Alembic commands ###
