repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-eradicate"]

  - repo: https://github.com/patrick91/pre-commit-alex
    rev: aa5da9e54b92ab7284feddeaf52edf14b1690de3
    hooks:
      - id: alex
        exclude: CHANGELOG.md

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: '.*\.mdx?$'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml

  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
